name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build for ARM64
        run: |
          go mod download
          GOOS=darwin GOARCH=arm64 go build -o mouse_launcher_darwin_arm64 main.go
          chmod +x mouse_launcher_darwin_arm64

      - name: Build for AMD64
        run: |
          GOOS=darwin GOARCH=amd64 go build -o mouse_launcher_darwin_amd64 main.go
          chmod +x mouse_launcher_darwin_amd64

      - name: Create universal binary
        run: |
          lipo -create -output mouse_launcher_darwin_universal mouse_launcher_darwin_amd64 mouse_launcher_darwin_arm64
          chmod +x mouse_launcher_darwin_universal

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mouse_launcher_darwin_arm64
            mouse_launcher_darwin_amd64
            mouse_launcher_darwin_universal
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 